### ISSUE TITLE
Dispatching - BIG ROCKS

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#523]
## Routing feature parity
- [x] Identify routing features wanted but missing in dispatching prototype
- [x] Identify routing features that are low-value and cause performance problems
- [x] URL generation (not part of prototype) - https://github.com/aspnet/Routing/issues/531

## Addressing Gaps
- [x] Add support for HTTP method filtering/disambiguation - https://github.com/aspnet/Routing/issues/535
- [x] Add a concept like MVC's `IActionConstraint` for dispatcher (CORS, Versioning, `[Consumes]`) - https://github.com/aspnet/Routing/issues/534

## MVC's Scenarios
- [x] Make MVC work on top of dispatcher with attribute routing
  - [x] MVC endpoint data source - https://github.com/aspnet/Routing/issues/527
  - [x] MVC IUrlHelper over dispatching - https://github.com/aspnet/Routing/issues/530
- [x] Add conventional-routing-like experience
- [x] Improve route-value-invalidation behavior (URL Generation)

## Enhancements to Middleware (Moved to 3.0)
~~Use Dispatcher for CORS - https://github.com/aspnet/Routing/issues/536~~
~~Use Dispatcher for AuthZ - https://github.com/aspnet/Routing/issues/537~~

## Performance
- [x] Setup routing benchmarking scenario
- [x] Setup dispatching benchmarking scenario
- [x] Dispatching micro-benchmarks - https://github.com/aspnet/Routing/issues/533
   -  [x] Simple matching
   -  [x] Complex matching
   -  [x] Stress-test matching (hundreds of routes)

## Testing
- [x] Refactor tests to support testing routing and dispatching without duplication

## Samples (Moved to 3.0)
~~Versioning with dispatching~~
~~Accessing matched dispatching route in middleware~~
~~MVC sample~~
~~CORS/AuthZ sample~~

## API
- [x] Public API review - https://github.com/aspnet/Routing/issues/538
- [x] XML documentation

**Comment by leastprivilege** [comment]
being able to attach authorization policies to routes would be a nice addition.

**Comment by rynowak** [comment]
@JamesNK @kichalla - I checked some checkboxes to give us credit what we've done. Feel free to correct anything you think I got wrong

**Comment by JamesNK** [comment]
New routing is still being worked on and we are not sure what it will look like yet. Right now we are working to get a first cut ready for 2.2 preview 1. After preview 1 documentation and blog posts will become more of a priority to gather feedback.

Routing is focused on HTTP requests. I'm not sure what plans there are for other protocols. @davidfowl?

**Comment by shaggygi** [comment]
@JamesNK  Thx for the reply.  I look forward to the preview and blog on coming details.

To provide a little more... I interpreted (and could be very wrong) that Bedrock and related is to provide a way to process bytes from different transports (e.g. ethernet, usb, serial, bluetooth, etc.), parse raw bytes to meaningful objects (based on various protocols) and allow routes/dispatches to certain parts of the application that can process data and return respective response.

If my interpretation is correct, this will be huge for embedded scenarios (not necessarily only IoT).  Use the older Modbus protocol (https://en.wikipedia.org/wiki/Modbus) for example.  This protocol usually has raw bytes transferred over a RS485 serial port connection (though there is also Modbus/IP).  Within the packet, there is a specific byte (Function) that represents what the Data bytes are used for.  Meaning, the Function value informs what command (e.g. read coils/holding registers) is being sent to the device.  

I was thinking the new dispatch would allow us to map how to route these types of message.  Am I completely off or is this in the plans for 2.2 RTM or 3.0?

Thanks again

**Comment by davidfowl** [comment]
> To provide a little more... I interpreted (and could be very wrong) that Bedrock and related is to provide a way to process bytes from different transports (e.g. ethernet, usb, serial, bluetooth, etc.), parse raw bytes to meaningful objects (based on various protocols) and allow routes/dispatches to certain parts of the application that can process data and return respective response.

This is correct.

> I was thinking the new dispatch would allow us to map how to route these types of message. Am I completely off or is this in the plans for 2.2 RTM or 3.0?

The name dispatcher is overly generic for what this is. This is specifically about routing so it'll apply to anything HTTP related but nothing more. I don't know how you'd generically apply routes to arbitrary protocols without inventing your own protocol that supported routes.

**Comment by rynowak** [comment]
I think we'd try to reuse some of the infrastructure and learnings for other systems that are based on a hierarchical address space.

However, I think developers generally want to system that exposes the details of the underlying protocol - in this case HTTP with notions like URL paths and HTTP verbs. Trying to make something totally generic might end up being un-useful.

**Comment by rynowak** [comment]
Updated this again based on the adjusted scope. The other real remaining thing here is xml docs for 2.2

**Comment by rynowak** [comment]
> Identify routing features wanted but missing in dispatching prototype

FYI I went through the list of closed issues and identified 3 that seem relevant but were closed long ago. This isn't a promise to do them, just to rethink them.

**Comment by rynowak** [comment]
Closing this as all of the individual items have been addressed in some form.
